-- reset database
DELETE FROM Child;
DELETE FROM Toy;
DROP TABLE IF EXISTS Child;
DROP TABLE IF EXISTS Toy;

CREATE TABLE `Child` (
    `ChildId` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    `Name`  VARCHAR NOT NULL,
    `Happy`    INTEGER NOT NULL
);

CREATE TABLE `Toy` (
    `ToyId` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    `Name`    VARCHAR NOT NULL,
    `ChildId`  INTEGER NOT NULL,
    FOREIGN KEY(`ChildId`) REFERENCES `Child`(`ChildId`)
);